# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Administrator/LAB02/LAB02.cache/wt [current_project]
set_property parent.project_path C:/Users/Administrator/LAB02/LAB02.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/Administrator/LAB02/LAB02.srcs/sources_1/new/Structural_FA.sv
  C:/Users/Administrator/LAB02/LAB02.srcs/sources_1/new/FA_TwoBit.sv
}
read_xdc {{C:/Users/Administrator/Desktop/Basys3 (1).xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Administrator/Desktop/Basys3 (1).xdc}}]

synth_design -top FA_TwoBit -part xc7a35tcpg236-1
write_checkpoint -noxdef FA_TwoBit.dcp
catch { report_utilization -file FA_TwoBit_utilization_synth.rpt -pb FA_TwoBit_utilization_synth.pb }
